// 构建脚本：将 index.html 生成为 TypeScript 模块
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(__dirname, 'index.html'), 'utf-8');

const content = `// AUTO-GENERATED by build-ui.ts — DO NOT EDIT
export const html: string = ${JSON.stringify(html)};
`;

writeFileSync(join(__dirname, 'ui.ts'), content, 'utf-8');
console.log(`✓ ui.ts generated (${(content.length / 1024).toFixed(0)} KB)`);
